#!/usr/bin/env python

"""
This script launches the rflow using otaviog/plant-segmentation
docker environment in the current directory. Requires Linux and NVidia docker.
"""

import os
import argparse
import grp
from pathlib import Path

CONTAINER_NAME = "rflow.docker"


def _main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mapping-dir")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Shows docker command")
    parser.add_argument(
        "--rm", help="removes the docker container", action="store_true")
    parser.add_argument("rest", nargs='*')

    args = parser.parse_args()

    if args.rm:
        os.system("docker stop {}".format(CONTAINER_NAME))
        os.system("docker rm {}".format(CONTAINER_NAME))

    docker_grp = grp.getgrnam('docker')[2]
    pwd = Path(".").absolute()
    home_dir = str(Path.home())

    cmd = """docker run --gpus all --volume={pwd}:/exec
    --user={uid}:{gid}
    --env="DISPLAY"
    -e NVIDIA_DRIVER_CAPABILITIES=all
    -e XAUTHORITY
    --volume="/etc/group:/etc/group:ro" 
    --volume="/etc/passwd:/etc/passwd:ro" 
    --volume="/etc/shadow:/etc/shadow:ro" 
    --volume="/etc/sudoers.d:/etc/sudoers.d:ro" 
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"
    --ipc=host
    --volume="{home_dir}:{home_dir}"
    --workdir=/exec
    -it otaviog/plant-segmentation /opt/conda/bin/rflow {args}""".format(
        pwd=pwd, uid=os.getuid(),
        gid=docker_grp,
        container_name=CONTAINER_NAME,
        args=" ".join(args.rest),
        home_dir=home_dir)
    cmd = " ".join(cmd.split())
    if args.verbose:
        print(cmd)
    os.system(cmd)


if __name__ == '__main__':
    _main()
