name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install opencv-python==4.4.0.46
        pip install -r requirements-dev.txt
        pip install ./module
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        make -f tasks.mk pylint
